### PR TITLE
fix(calendar): use CalendarEntityDescription instead of base EntityDescription

### LINKED ISSUE #49: Calendar entity fails to register: `AttributeError: 'EntityDescription' object has no attribute 'initial_color'`
# Calendar entity fails to register: `AttributeError: 'EntityDescription' object has no attribute 'initial_color'`

## Summary

Since calendar support was merged in #20 (Feb 2026), the `calendar.grocy` entity has been failing to register on every HA startup with `AttributeError: 'EntityDescription' object has no attribute 'initial_color'`. The `sensor.*`, `update.*`, and other platforms set up fine — only `calendar.*` is missing.

This seems to affect every install on a recent HA core (the `initial_color` lookup happens during `entity_registry.async_get_or_create` when the calendar platform calls `get_initial_entity_options` for any new calendar entity).

## Reproduction

Latest HA Core (2026.x). Add the Grocy integration. Check the log:

```
ERROR (MainThread) [homeassistant.components.calendar] Error adding entity None for domain calendar with platform grocy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 911, in _async_add_entity
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1417, in async_get_or_create
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 534, in get_initial_entity_options
    if self.initial_color is None:
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 529, in initial_color
    return self.entity_description.initial_color
AttributeError: 'EntityDescription' object has no attribute 'initial_color'
```

`ha_search_entities("grocy")` returns the sensor and update entities but no `calendar.*`.

Reproduces on every HA restart and every `Reload integration` of Grocy.

## Root cause

`custom_components/grocy/calendar.py` line 83 (v1.13.0) constructs the entity description with the base `EntityDescription` class:

```python
self.entity_description = EntityDescription(
    key="calendar",
    name="Grocy calendar",
)
```

HA's `CalendarEntity` reads `entity_description.initial_color` to set the default UI color for new calendar entities. The base `EntityDescription` has no `initial_color` field; `CalendarEntityDescription` (subclass exported from `homeassistant.components.calendar`) has `initial_color: str | None = None`. Using the wrong class makes the attribute access raise.

The integration's own comment on the same block notes the description is set "for coordinator compatibility (even though calendar doesn't use coordinator data)" — i.e., the field isn't actually consumed by anything in this integration. The fix is either to use the correct subclass or drop the four lines entirely.

## Proposed fix

One-line change — swap `EntityDescription` for `CalendarEntityDescription` in the same `calendar.py`. Diff in the linked PR.

## Affected versions

v1.13.0 (latest stable) and v1.14.0-pre. Likely all calendar-supporting versions back to PR #20.

## Workaround

Locally edit `custom_components/grocy/calendar.py` per the linked PR and restart HA.

### PR DESCRIPTION
**Pull request by alexlmiller**
# Fix calendar entity registration: use CalendarEntityDescription

## Summary

The `calendar.grocy` entity has been failing to register since calendar support was added in #20, with `AttributeError: 'EntityDescription' object has no attribute 'initial_color'`. HA's `CalendarEntity` reads `entity_description.initial_color` during entity registration to set the calendar's default UI color; the base `EntityDescription` doesn't have that field but `CalendarEntityDescription` does.

Closes #49.

## Change

Two lines in `custom_components/grocy/calendar.py`:

- Import `CalendarEntityDescription` from `homeassistant.components.calendar` (already imported alongside `CalendarEntity` and `CalendarEvent`).
- Use it on line 83 in place of `EntityDescription`.

## Verficiation

- [ ] `pytest` passes
- [ ] Fresh install: add Grocy integration → `calendar.grocy` shows up with no `Error adding entity None for domain calendar with platform grocy` in the log
- [ ] Existing install: HA restart → `calendar.grocy` registers successfully (it has been silently absent for users on the affected versions)

### CODE REVIEW

**Comment by Rudd-O** [comment]
Even with the patch (which does fix the color problem) I still get this:

```
Apr 29 14:54:05 assistant hass[2661581]: 2026-04-29 14:54:05.917 ERROR (MainThread) [custom_components.grocy.coordinator] Failed to update meal_plan: 1 validation error for MealPlanResponse
Apr 29 14:54:05 assistant hass[2661581]: product_qu_id
Apr 29 14:54:05 assistant hass[2661581]:   Input should be a valid string [type=string_type, input_value=10, input_type=int]
Apr 29 14:54:05 assistant hass[2661581]:     For further information visit https://errors.pydantic.dev/2.12/v/string_type
```

The meal plan entity calendar is, of course, unavailable.

I am using latest HA and latest Grocy and latest prerelease of this integration (plus the patch).

What information is required of me to help fix this issue?

EDIT: actually it's not the meal plan calendar that is unavailable.  It is the to-do list that remains unavailable.  This patch fixes the calendar and that works fine.

**Comment by alexlmiller** [comment]
@Rudd-O ok, os confirming you don't need anything else from me on that part? I'm happy to dig into the to-do list one too but hadn't hit it directly

**Comment by alexlmiller** [comment]
@Rudd-O I dug into the to-do list availability error too.

The failing field is from the meal plan payload used by the to-do entity:

```
MealPlanResponse.product_qu_id
Input should be a valid string [type=string_type, input_value=10, input_type=int]
```

Root cause:

- Home Assistant installs custom integration dependencies from `custom_components/grocy/manifest.json`
- `manifest.json` was still pinned to `grocy-py==0.0.7`
- `grocy-py==0.0.7` defines `product_qu_id` as `str | None`
- Grocy can return this as an integer, which trips Pydantic validation
- `grocy-py==0.0.8` already fixes this by accepting `int | str | None`

I pushed a second commit to this PR:

```
aa80df2 fix: require grocy-py 0.0.8
```

That updates the manifest requirement to match `pyproject.toml`, so Home Assistant should install the fixed client library. This should address the unavailable to-do entity case, while the first commit handles the original calendar entity registration issue.

**Comment by iamkarlson** [comment]
Thanks @alexlmiller! Rebased onto current main, with one tiny style fix — ruff wanted the multi-import line wrapped. Your `CalendarEntityDescription` fix and the manifest.json grocy-py bump both landed via 91bd4b4 (the grocy-py bump later jumped past 0.0.8 → 0.1.0 in the 1.10.0 release). Calendar entity now registers cleanly. Closes #49.

Closing — credit on the commits and the upcoming release notes.
